version: '3.8'
services:
  db:
    image: postgres:alpine
    container_name: postgres_local
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "#Bismillah_01"
      POSTGRES_DB: clinic
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
